<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Description>SDK for loading and modifying Minecraft worlds</Description>
    <Copyright>Copyright © 2011-2015 Justin Aquadro</Copyright>
    <Authors>Justin Aquadro, Simon Stevenson</Authors>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <Version>2.0.0-alpha</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iconic.Zlib.Netstandard" Version="1.0.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.9" />
  </ItemGroup>

</Project>
